# List 
The sequence of data elements stored in the list need not to be of the same type.

In [3]:
bin_operatorSys=['WIndows','Linux','Mac','Phoenix']

In [8]:
bin_operatorSys[1:3]

['Linux', 'Mac']

In [7]:
for anOS in bin_operatorSys:
    print (anOS + "_OS")

WIndows_OS
Linux_OS
Mac_OS
Phoenix_OS


# Tuples
Tuples consist of several elements surrounded by ().

In [9]:
bin_processors=('Ryzen','Intel','SnapDragon','Mediatek','Bionic')
bin_processors[2]

'SnapDragon'

# Dictionary
The Value can be an element of any type, for example, a number or string.

In [20]:
bin_approach={
    "manual_aprroach":"running",
    "approved_approach":"flying",
    "refused_approach":"teleport"
}

In [21]:
print(bin_approach)

{'manual_aprroach': 'running', 'approved_approach': 'flying', 'refused_approach': 'teleport'}


In [22]:
bin_approach.get('refuse_approach')

In [23]:
bin_approach['approved_approach']

'flying'

To update a value associated with a key, use the following code:

In [24]:
bin_approach['approved_approach']="dash"
print(bin_approach)

{'manual_aprroach': 'running', 'approved_approach': 'dash', 'refused_approach': 'teleport'}



# Sets
A set is defined as a collection od element that can be of different types.{}

In [25]:
running={'naruto','jackass'}
print(running)

{'jackass', 'naruto'}


# DataFrames
data frame is a data structure used to store tabular data available in Python's pandas package.

In [29]:
import pandas as pd
df=pd.DataFrame([['20xx-071','Informatika',300,True],['20xx-081','Sistem Informasi',500,False],['20xx-041','Arsitektur',800,True]])
df.columns=['NIM','Prodi','Member','Status']
df

NIM             Prodi  Member  Status
0  20xx-071       Informatika     300    True
1  20xx-081  Sistem Informasi     500   False
2  20xx-041        Arsitektur     800    True

column selection

In [34]:
df[['Prodi','Status']]

Prodi  Status
0       Informatika    True
1  Sistem Informasi   False
2        Arsitektur    True

In [37]:
df.iloc[:,1]

0         Informatika
1    Sistem Informasi
2          Arsitektur
Name: Prodi, dtype: object

Row selection

In [38]:
df.iloc[0:1,:]

NIM        Prodi  Member  Status
0  20xx-071  Informatika     300    True

In [40]:
df[df.Member>500]

NIM       Prodi  Member  Status
2  20xx-041  Arsitektur     800    True

# Matrix
A Matrix is a two-dimensional data structure with a fixed number of columns and rows.

In [42]:
import numpy as np
myMatrix=np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [43]:
print(type(myMatrix))

<class 'numpy.ndarray'>


# Vector

In [44]:
#using a Python list
myVector=[22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [45]:
print(type(myVector))

<class 'list'>


In [47]:
#using a numpy array
myVector=np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [48]:
print(type(myVector))

<class 'numpy.ndarray'>


# Stack

In [73]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)


## Populate stack

In [74]:
stack=Stack()
stack.push('snsv')
stack.push('Lenobo')
stack.push('Toserba')
stack.push('Misi')
stack.push('aser')

## pop

In [75]:
stack.pop()

'aser'

In [76]:
stack.isEmpty()

False

# Queue

In [77]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [78]:
queue=Queue()

In [79]:
queue.enqueue('snsv')

In [80]:
queue.enqueue('Lenobo')

In [81]:
queue.enqueue('Toserba')

In [82]:
print(queue.size())

3


In [83]:
print(queue.dequeue())

Red


In [84]:
print(queue.dequeue())

Lenobo
